# Generated by Django 5.1.3 on 2024-12-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posting_date_posting_schedule_posing_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting_schedule',
            old_name='posing_time',
            new_name='posting_time',
        ),
    ]
