# Generated by Django 5.1.3 on 2024-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_posing_time_posting_schedule_posting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting_schedule',
            name='posting_time',
            field=models.TextField(max_length=30),
        ),
    ]
