# Generated by Django 5.1.3 on 2024-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_common_promotional_message_blog_common_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='common_promotional_message',
            new_name='common_promo',
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='gpt_prompt',
            field=models.TextField(default='', max_length=2024),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='promo_msg',
            field=models.TextField(default='', max_length=2024),
        ),
    ]
