# Generated by Django 5.1.3 on 2024-12-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_common_promotional_message_blog_common_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting_schedule',
            name='language',
            field=models.TextField(default='English', max_length=200),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=100)),
                ('posting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posting_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=100)),
                ('posting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posting_schedule')),
            ],
        ),
    ]
