# Generated by Django 5.1.3 on 2024-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posting_schedule_language_category_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cloud_config',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='openai_api',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='runway_api',
            field=models.TextField(default='', max_length=100),
        ),
    ]
