# Generated by Django 5.1.3 on 2024-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_cloud_config_blog_openai_api_blog_runway_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting_schedule',
            name='content_type',
            field=models.TextField(default=' ', max_length=10),
        ),
    ]
