# Generated by Django 5.1.3 on 2024-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_posting_schedule_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting_schedule',
            name='story_idea',
            field=models.TextField(default='', max_length=2024),
        ),
    ]
