# Generated by Django 5.1.3 on 2024-12-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posting_schedule_story_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting_schedule',
            name='hook_animation_instructions',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='hook_dalle',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='hook_scene',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='hook_script',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='hook_ssml',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='last_animation_instructions',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='last_dalle',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='last_scene',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='last_script',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='last_ssml',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='storyline',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='posting_schedule',
            name='content_type',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripts', models.TextField(max_length=2048)),
                ('scenes', models.TextField(max_length=2048)),
                ('ssml', models.TextField(max_length=2048)),
                ('animation_instructions', models.TextField(max_length=2048)),
                ('dalle_prompts', models.TextField(max_length=2048)),
                ('posting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posting_schedule')),
            ],
        ),
    ]
