# Generated by Django 5.1.3 on 2024-12-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_posting_schedule_hook_animation_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(default='', max_length=2048)),
                ('scene', models.TextField(default='', max_length=2048)),
                ('ssml', models.TextField(default='', max_length=2048)),
                ('animation_instruction', models.TextField(default='', max_length=2048)),
                ('dalle_prompt', models.TextField(default='', max_length=2048)),
                ('posting_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posting_schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Scenes',
        ),
    ]
