# Generated by Django 5.1.3 on 2024-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_scene_delete_scenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='form4_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posting_schedule',
            name='posting_time_passed',
            field=models.BooleanField(default=False),
        ),
    ]
