# Generated by Django 5.1.3 on 2024-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_form4_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting_schedule',
            name='posting_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
